<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        //Users
        DB::table('users')->insert([
            [
                'name' => 'Khach Hang',
                'email' => 'chuduchoang@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987654321',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0123456789',
                "role" => 'admin',
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tien Duc',
                'email' => 'tienduc@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987654541',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Trung Trinh',
                'email' => 'trungtrinh@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0986554541',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hoang Hiep',
                'email' => 'hoanghiep@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987654111',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minh Hieu',
                'email' => 'minhhieu@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987654211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Huy',
                'email' => 'huy@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987334211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minh',
                'email' => 'minh@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0997654211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dung',
                'email' => 'dung@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987754211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'manh',
                'email' => 'manh@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987666211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'vu',
                'email' => 'vu@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987754211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuan',
                'email' => 'tuan@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987555211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hai',
                'email' => 'hai@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0988888211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nam',
                'email' => 'nam@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0986666211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lam',
                'email' => 'lam@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0887654211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hoang',
                'email' => 'hoang@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0980054211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuan Anh',
                'email' => 'tuananh@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987600211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vy',
                'email' => 'vy@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0999654211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phuong',
                'email' => 'phuong@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987554211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lan',
                'email' => 'lan@gmail.com',
                'password' => Hash::make('12345678'),
                'phone' => '0987924211',
                "role" => null,
                'status' => "0",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        //Driving Licenses
        DB::table('driving_licenses')->insert([
            [
                'user_id' => 1,
                'license_number' => '083947193757',
                'thumbnail_1' => 'uploadLicenses/mattruoc.jpg',
                'thumbnail_2' => 'uploadLicenses/matsau.jpg',
                'issue_date' => "2023-07-12",
                'expiration_date' => "2030-07-12",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'license_number' => '083947193999',
                'thumbnail_1' => 'uploadLicenses/mattruoc.jpg',
                'thumbnail_2' => 'uploadLicenses/matsau.jpg',
                'issue_date' => "2020-07-12",
                'expiration_date' => "2028-07-12",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        //Brands
        DB::table('brands')->insert([
            [
                'name' => 'Audi',
                'slug' => Str::slug('Audi'),
                'icon' => 'images/icons/Audi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BMW',
                'slug' => Str::slug('bmw'),
                'icon' => 'images/icons/BMW.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cadillac',
                'slug' => Str::slug('Cadillac'),
                'icon' => 'images/icons/Cadillac.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ford',
                'slug' => Str::slug('Ford'),
                'icon' => 'images/icons/Ford.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Honda',
                'slug' => Str::slug('Honda'),
                'icon' => 'images/icons/Honda.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hyundai',
                'slug' => Str::slug('Hyundai'),
                'icon' => 'images/icons/Hyundai.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jaguar',
                'slug' => Str::slug('Jaguar'),
                'icon' => 'images/icons/Jaguar.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'KIA',
                'slug' => Str::slug('KIA'),
                'icon' => 'images/icons/KIA.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lamborghini',
                'slug' => Str::slug('Lamborghini'),
                'icon' => 'images/icons/Lamborghini.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Land-Rover',
                'slug' => Str::slug('Land-Rover'),
                'icon' => 'images/icons/Land-Rover.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lexus',
                'slug' => Str::slug('Lexus'),
                'icon' => 'images/icons/Lexus.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mercedes-Benz',
                'slug' => Str::slug('Mercedes-Benz'),
                'icon' => 'images/icons/Mercedes-Benz.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mini',
                'slug' => Str::slug('Mini'),
                'icon' => 'images/icons/Mini.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mitsubishi',
                'slug' => Str::slug('Mitsubishi'),
                'icon' => 'images/icons/Mitsubishi.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nissan',
                'slug' => Str::slug('Nissan'),
                'icon' => 'images/icons/Nissan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peugeot',
                'slug' => Str::slug('Peugeot'),
                'icon' => 'images/icons/Peugeot.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        //Car Type
        DB::table('cartypes')->insert([
            [
                'name' => 'Car',
                'slug' => Str::slug('car'),
                'icon' => 'images/select-form/car.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Convertible',
                'slug' => Str::slug('convertible'),
                'icon' => 'images/select-form/convertible.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Coupe',
                'slug' => Str::slug('coupe'),
                'icon' => 'images/select-form/coupe.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hatchback',
                'slug' => Str::slug('hatchback'),
                'icon' => 'images/select-form/hatchback.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Limousine',
                'slug' => Str::slug('limousine'),
                'icon' => 'images/select-form/limousine.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mini bus',
                'slug' => Str::slug('mini bus'),
                'icon' => 'images/select-form/minibus.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MPV',
                'slug' => Str::slug('mpv'),
                'icon' => 'images/select-form/mpv.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pick Up',
                'slug' => Str::slug('pick up'),
                'icon' => 'images/select-form/pickup.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sedan',
                'slug' => Str::slug('sedan'),
                'icon' => 'images/select-form/sedan.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sports car',
                'slug' => Str::slug('sports car'),
                'icon' => 'images/select-form/sportscar.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUV',
                'slug' => Str::slug('suv'),
                'icon' => 'images/select-form/suv.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Van',
                'slug' => Str::slug('van'),
                'icon' => 'images/select-form/van.png',
                'description' => 'Loai xe ...',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        //Cars
        DB::table('cars')->insert([
            [
                'license_plate' => '30A-11111',
                'model' => 'Audi R7',
                'slug' => Str::slug('audir7'),
                'price' => '100',
                'desposit' => '2500',
                'brand_id' => 1,
                'carType_id' => 10,
                'thumbnail' => 'images/cars/Audi R7 1.jpg',
                'fuelType' => 'Diozen',
                'transmission' => 'Auto',
                'km_limit' => '300',
                'modelYear' => '2022',
                'reverse_sensor' => '1',
                'airConditioner' => '0',
                'driverAirbag' => '0',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'The all-new 2020 Audi RS7 Sportback represents the most powerful version of the flagship A7 sedan from Audi. The RS7 2020 has a more spacious body and separate high-performance equipment to help increase its competitiveness with rivals such as the Mercedes-AMG GT63 and Porsche Panamera Turbo.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-99999',
                'model' => 'Audi R8',
                'slug' => Str::slug('audir8'),
                'price' => '110',
                'desposit' => '1800',
                'brand_id' => 1,
                'carType_id' => 10,
                'thumbnail' => 'images/cars/Audi R8 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'The all-new 2020 Audi RS8 Sportback represents the most powerful version of the flagship A7 sedan from Audi. The RS7 2020 has a more spacious body and separate high-performance equipment to help increase its competitiveness with rivals such as the Mercedes-AMG GT63 and Porsche Panamera Turbo.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-22222',
                'model' => 'BMW i8',
                'slug' => Str::slug('bmwi8'),
                'price' => '120',
                'desposit' => '3800',
                'brand_id' => 2,
                'carType_id' => 3,
                'thumbnail' => 'images/cars/BMW i8 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2019',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '2',
                'status' => '0',
                'description' => 'The BMW i8 is a plug-in hybrid sports car developed by BMW, Germany. The production version of the BMW i8 was first unveiled at the 2013 Frankfurt Motor Show and officially went on sale from June 2014 in Germany. Up to now, the BMW i8 is still in its first generation.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-33333',
                'model' => 'BMW X4',
                'slug' => Str::slug('bmwx4'),
                'price' => '130',
                'desposit' => '3500',
                'brand_id' => 2,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/BMW X4 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2011',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'The BMW i8 is a plug-in hybrid sports car developed by BMW, Germany. The production version of the BMW i8 was first unveiled at the 2013 Frankfurt Motor Show and officially went on sale from June 2014 in Germany. Up to now, the BMW i8 is still in its first generation.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-44444',
                'model' => 'Cadillac cts',
                'slug' => Str::slug('cadillaccts'),
                'price' => '140',
                'desposit' => '2200',
                'brand_id' => 3,
                'carType_id' => 9,
                'thumbnail' => 'images/cars/Cadillac cts 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Dubbed a "golden sedan" in the luxury car village in the US. Currently, the Cadillac CTS 2023 model has been launched by the company with fierce competition with many famous models such as: BMW 5 Series, Audi A6, Mercedes-Benz E-Class, ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-44444',
                'model' => 'Cadillac escalade',
                'slug' => Str::slug('cadillacescalade'),
                'price' => '150',
                'desposit' => '2100',
                'brand_id' => 3,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Cadillac-escalade-1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Dubbed a "golden sedan" in the luxury car village in the US. Currently, the Cadillac CTS 2023 model has been launched by the company with fierce competition with many famous models such as: BMW 5 Series, Audi A6, Mercedes-Benz E-Class, ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-55555',
                'model' => 'Ford 150',
                'slug' => Str::slug('ford150'),
                'price' => '160',
                'desposit' => '2500',
                'brand_id' => 4,
                'carType_id' => 8,
                'thumbnail' => 'images/cars/Ford 150 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'The New Generation Ford Ranger is the best pickup truck ever. Powerful, smart and versatile, the Next Generation Ranger is perfect for work, home or just enjoying life.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-44444',
                'model' => 'Honda brv',
                'slug' => Str::slug('hondabrv'),
                'price' => '170',
                'desposit' => '2000',
                'brand_id' => 5,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Honda brv 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Honda BR-V is a small 7-seat MPV model of Honda, Japan. First introduced in August 2015 at the Gaikindo Indonesia international auto show, so far the Honda BRV has been sold mainly in Asian markets, such as India, Pakistan, Malaysia, Indonesia, the Philippines, and South Korea. Fly...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-66666',
                'model' => 'Honda crv',
                'slug' => Str::slug('hondacrv'),
                'price' => '180',
                'desposit' => '2100',
                'brand_id' => 5,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Honda crv 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2016',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Honda BR-V is a small 7-seat MPV model of Honda, Japan. First introduced in August 2015 at the Gaikindo Indonesia international auto show, so far the Honda BRV has been sold mainly in Asian markets, such as India, Pakistan, Malaysia, Indonesia, the Philippines, and South Korea. Fly...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-77777',
                'model' => 'Huyndai creta',
                'slug' => Str::slug('huyndaicreta'),
                'price' => '190',
                'desposit' => '2000',
                'brand_id' => 6,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Huyndai creta 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto CVT',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Hyundai Creta has dimensions Length x Width x Height respectively 4,315 x 1,790 x 1,660 (mm) with a ground clearance of 200 (mm), considered a "little Tucson" with a black grille or hidden LED position lights. .Light clusters continue to be placed low, while the rear is still the appearance of the characteristic polygonal light cluster.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-88888',
                'model' => 'Huyndai palisade',
                'slug' => Str::slug('huyndaipalisade'),
                'price' => '110',
                'desposit' => '2200',
                'brand_id' => 6,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Huyndai palisade 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Hyundai Creta has dimensions Length x Width x Height respectively 4,315 x 1,790 x 1,660 (mm) with a ground clearance of 200 (mm), considered a "little Tucson" with a black grille or hidden LED position lights. .Light clusters continue to be placed low, while the rear is still the appearance of the characteristic polygonal light cluster.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-12345',
                'model' => 'Jaguar F-Type',
                'slug' => Str::slug('jaguarf-type'),
                'price' => '120',
                'desposit' => '2300',
                'brand_id' => 7,
                'carType_id' => 3,
                'thumbnail' => 'images/cars/Jaguar F-Type 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '2',
                'status' => '0',
                'description' => 'Jaguar F-Type is a two-door, two-seat sports car produced by British luxury car manufacturer Jaguar and was first launched in 2013. Up to now, this luxury sports car has only been launched. there is 1 generation.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-44444',
                'model' => 'Jaguar XF',
                'slug' => Str::slug('jaguarxf'),
                'price' => '130',
                'desposit' => '2300',
                'brand_id' => 7,
                'carType_id' => 9,
                'thumbnail' => 'images/cars/Jaguar XF 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'The new Jaguar XF features an all-new interior, enhanced connectivity, greater elegance and refinement. The new cockpit design is more dynamic and focused more on the driver.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-44444',
                'model' => 'KIA EV6',
                'slug' => Str::slug('kiaev6'),
                'price' => '140',
                'desposit' => '2550',
                'brand_id' => 8,
                'carType_id' => 4,
                'thumbnail' => 'images/cars/KIA EV6 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '4',
                'status' => '0',
                'description' => 'Kia EV6 is a small electric Crossover Coupe manufactured by Kia Motor - Korea. Some images of this car were revealed by the car company in February 2021.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-56774',
                'model' => 'KIA EV9',
                'slug' => Str::slug('kiaev9'),
                'price' => '150',
                'desposit' => '2000',
                'brand_id' => 8,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/KIA EV9 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Kia EV9 is a small electric Crossover Coupe manufactured by Kia Motor - Korea. Some images of this car were revealed by the car company in February 2021.',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09876',
                'model' => 'Lamborghini Aventador',
                'slug' => Str::slug('lamborghiniaventador'),
                'price' => '160',
                'desposit' => '3500',
                'brand_id' => 9,
                'carType_id' => 10,
                'thumbnail' => 'images/cars/Lamborghini Aventador 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2017',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '2',
                'status' => '0',
                'description' => 'Aventador LP 700-4 Roadster 2013 đã được công bố vào ngày 27 tháng 12 năm 2012, trang bị động cơ V12 giống như phiên bản coupé, Lamborghini lại tuyên bố rằng nó có thể đạt tốc độ 97 km/h (60 mph) trong vòng chưa đầy 3 giây và tốc độ tối đa hơn 350 km/h (217 mph).',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-56884',
                'model' => 'Lamborghini Huracan',
                'slug' => Str::slug('lamborghinihuracan'),
                'price' => '170',
                'desposit' => '3500',
                'brand_id' => 9,
                'carType_id' => 10,
                'thumbnail' => 'images/cars/Lamborghini Huracan 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2020',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '2',
                'status' => '0',
                'description' => 'Huracan LP 700-4 Roadster 2013 đã được công bố vào ngày 27 tháng 12 năm 2012, trang bị động cơ V12 giống như phiên bản coupé, Lamborghini lại tuyên bố rằng nó có thể đạt tốc độ 97 km/h (60 mph) trong vòng chưa đầy 3 giây và tốc độ tối đa hơn 350 km/h (217 mph).',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-56674',
                'model' => 'Land Rover Discovery',
                'slug' => Str::slug('landroverdiscovery'),
                'price' => '180',
                'desposit' => '3200',
                'brand_id' => 10,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Land Rover Discovery 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2015',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Mot loai xe ban tai ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-50774',
                'model' => 'Range Rover Evoque',
                'slug' => Str::slug('rangeroverevoque'),
                'price' => '190',
                'desposit' => '3200',
                'brand_id' => 10,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Range Rover Evoque 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2014',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Mot loai xe ban tai ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-56774',
                'model' => 'Lexus IS 300',
                'slug' => Str::slug('lexusis300'),
                'price' => '110',
                'desposit' => '3100',
                'brand_id' => 11,
                'carType_id' => 9,
                'thumbnail' => 'images/cars/Lexus IS 300 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2013',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '4',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'Lexus NX',
                'slug' => Str::slug('lexusnx'),
                'price' => '120',
                'desposit' => '3100',
                'brand_id' => 11,
                'carType_id' => 10,
                'thumbnail' => 'images/cars/Lexus NX 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'Mercedes C-Class',
                'slug' => Str::slug('mercedesc-class'),
                'price' => '130',
                'desposit' => '3050',
                'brand_id' => 12,
                'carType_id' => 9,
                'thumbnail' => 'images/cars/Mercedes C-Class 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'Mercedes-Benz GLC',
                'slug' => Str::slug('mercedesbenzglc'),
                'price' => '140',
                'desposit' => '3050',
                'brand_id' => 12,
                'carType_id' => 9,
                'thumbnail' => 'images/cars/Mercedes-Benz GLC 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2019',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09174',
                'model' => 'MINI Cooper Convertible',
                'slug' => Str::slug('minicooperconvertible'),
                'price' => '150',
                'desposit' => '2400',
                'brand_id' => 13,
                'carType_id' => 3,
                'thumbnail' => 'images/cars/MINI Cooper Convertible 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '2',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'MINI Cooper',
                'slug' => Str::slug('minicooper'),
                'price' => '160',
                'desposit' => '2400',
                'brand_id' => 13,
                'carType_id' => 3,
                'thumbnail' => 'images/cars/MINI Cooper 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '2',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-19774',
                'model' => 'Mitsubishi OUTLANDER',
                'slug' => Str::slug('mitsubishioutlander'),
                'price' => '170',
                'desposit' => '2150',
                'brand_id' => 14,
                'carType_id' => 4,
                'thumbnail' => 'images/cars/Mitsubishi OUTLANDER 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2020',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'Mitsubishi XPANDER',
                'slug' => Str::slug('mitsubishixpander'),
                'price' => '180',
                'desposit' => '2160',
                'brand_id' => 14,
                'carType_id' => 4,
                'thumbnail' => 'images/cars/Mitsubishi XPANDER 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-11774',
                'model' => 'Nissan Kicks e-power',
                'slug' => Str::slug('nissankickse-power'),
                'price' => '190',
                'desposit' => '2700',
                'brand_id' => 15,
                'carType_id' => 11,
                'thumbnail' => 'images/cars/Nissan Kicks e-power 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Floor',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09974',
                'model' => 'Nissan Navara',
                'slug' => Str::slug('nissannavara'),
                'price' => '110',
                'desposit' => '2700',
                'brand_id' => 15,
                'carType_id' => 8,
                'thumbnail' => 'images/cars/Nissan Navara 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2013',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'Peugeot 2008',
                'slug' => Str::slug('peugeot2008'),
                'price' => '120',
                'desposit' => '2600',
                'brand_id' => 16,
                'carType_id' => 4,
                'thumbnail' => 'images/cars/Peugeot 2008​ 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2018',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '5',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'license_plate' => '29A-09774',
                'model' => 'Peugeot 5008',
                'slug' => Str::slug('peugeot5008'),
                'price' => '130',
                'desposit' => '2600',
                'brand_id' => 16,
                'carType_id' => 4,
                'thumbnail' => 'images/cars/Peugeot 5008 1.jpg',
                'fuelType' => 'Electri',
                'transmission' => 'Auto',
                'km_limit' => '200',
                'modelYear' => '2012',
                'reverse_sensor' => '1',
                'airConditioner' => '1',
                'driverAirbag' => '1',
                'cDPlayer' => '1',
                'brakeAssist' => '1',
                'seats' => '7',
                'status' => '0',
                'description' => 'Mot loai xe dep ...',
                'rate' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

        //gallery
        DB::table('gallery')->insert([
            [
                'thumbnail' => 'images/gallery/Audi R7 2.jpg',
                'car_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Audi R7 3.jpg',
                'car_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Audi R7 4.jpg',
                'car_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Audi R8 2.jpg',
                'car_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Audi R8 3.jpg',
                'car_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Audi R8 4.jpg',
                'car_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/BMW i8 2.jpg',
                'car_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/BMW i8 3.jpg',
                'car_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/BMW i8 4.jpg',
                'car_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/BMW X4 2.jpg',
                'car_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/BMW X4 3.jpg',
                'car_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/BMW X4 4.jpg',
                'car_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Cadillac cts 2.jpg',
                'car_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Cadillac cts 3.jpg',
                'car_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Cadillac cts 4.jpg',
                'car_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Cadillac-escalade-2.jpg',
                'car_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Cadillac-escalade-3.jpg',
                'car_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Cadillac-escalade-4.jpg',
                'car_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Ford 150 2.jpg',
                'car_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Ford 150 3.jpg',
                'car_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Ford 150 4.jpg',
                'car_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Honda brv 2.jpg',
                'car_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Honda brv 3.jpg',
                'car_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Honda brv 4.jpg',
                'car_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Honda crv 2.jpg',
                'car_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Honda crv 3.jpg',
                'car_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Honda crv 4.jpg',
                'car_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Huyndai creta 2.jpg',
                'car_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Huyndai creta 3.jpg',
                'car_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Huyndai creta 4.jpg',
                'car_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Huyndai palisade 2.jpg',
                'car_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Huyndai palisade 3.jpg',
                'car_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Huyndai palisade 4.jpg',
                'car_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Jaguar F-Type 2.jpg',
                'car_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Jaguar F-Type 3.jpg',
                'car_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Jaguar F-Type 4.jpg',
                'car_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Jaguar XF 2.jpg',
                'car_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Jaguar XF 3.jpg',
                'car_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Jaguar XF 4.jpg',
                'car_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/KIA EV6 2.jpg',
                'car_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/KIA EV6 3.jpg',
                'car_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/KIA EV6 4.jpg',
                'car_id' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/KIA EV9 2.jpg',
                'car_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/KIA EV9 3.jpg',
                'car_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/KIA EV9 4.jpg',
                'car_id' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lamborghini Aventador 2.jpg',
                'car_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lamborghini Aventador 3.jpg',
                'car_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lamborghini Aventador 4.jpg',
                'car_id' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lamborghini Huracan 2.jpg',
                'car_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lamborghini Huracan 3.jpg',
                'car_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lamborghini Huracan 4.jpg',
                'car_id' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Land Rover Discovery 2.jpg',
                'car_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Land Rover Discovery 3.jpg',
                'car_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Land Rover Discovery 4.jpg',
                'car_id' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Range Rover Evoque 2.jpg',
                'car_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Range Rover Evoque 3.jpg',
                'car_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Range Rover Evoque 4.jpg',
                'car_id' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lexus IS 300 2.jpg',
                'car_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lexus IS 300 3.jpg',
                'car_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lexus IS 300 4.jpg',
                'car_id' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lexus NX 2.jpg',
                'car_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lexus NX 3.jpg',
                'car_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Lexus NX 4.jpg',
                'car_id' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mercedes C-Class 2.jpg',
                'car_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mercedes C-Class 3.jpg',
                'car_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mercedes C-Class 4.jpg',
                'car_id' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mercedes-Benz GLC 2.jpg',
                'car_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mercedes-Benz GLC 3.jpg',
                'car_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mercedes-Benz GLC 4.jpg',
                'car_id' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/MINI Cooper Convertible 2.jpg',
                'car_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/MINI Cooper Convertible 3.jpg',
                'car_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/MINI Cooper Convertible 4.jpg',
                'car_id' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/MINI Cooper 2.jpg',
                'car_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/MINI Cooper 3.jpg',
                'car_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/MINI Cooper 4.jpg',
                'car_id' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mitsubishi OUTLANDER 2.jpg',
                'car_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mitsubishi OUTLANDER 3.jpg',
                'car_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mitsubishi OUTLANDER 4.jpg',
                'car_id' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mitsubishi XPANDER 2.jpg',
                'car_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mitsubishi XPANDER 3.jpg',
                'car_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Mitsubishi XPANDER 4.jpg',
                'car_id' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Nissan Kicks e-power 2.jpg',
                'car_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Nissan Kicks e-power 3.jpg',
                'car_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Nissan Kicks e-power 4.jpg',
                'car_id' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Nissan Navara 2.jpg',
                'car_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Nissan Navara 3.jpg',
                'car_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Nissan Navara 4.jpg',
                'car_id' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Peugeot 2008 2.jpg',
                'car_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Peugeot 2008 3.jpg',
                'car_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Peugeot 2008 4.jpg',
                'car_id' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Peugeot 5008 2.jpg',
                'car_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Peugeot 5008 3.jpg',
                'car_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'thumbnail' => 'images/gallery/Peugeot 5008 4.jpg',
                'car_id' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        //car Review
//        DB::table('carReview')->insert([
//            [
//                'message' => 'Xe rat moi',
//                'score' => '4',
//                'user_id' => 1,
//                'car_id' => 1,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'message' => 'Xe rat moi',
//                'score' => '5',
//                'user_id' => 2,
//                'car_id' => 2,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//        ]);

        //rentalRate
        DB::table('rentalrate')->insert([
            [
                'car_id' => 1,
                'rental_type' => 'rent by day',
                'price' => '100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 1,
                'rental_type' => 'rent by hour',
                'price' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 2,
                'rental_type' => 'rent by day',
                'price' => '110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 2,
                'rental_type' => 'rent by hour',
                'price' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 3,
                'rental_type' => 'rent by day',
                'price' => '120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 3,
                'rental_type' => 'rent by hour',
                'price' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 4,
                'rental_type' => 'rent by day',
                'price' => '130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 4,
                'rental_type' => 'rent by hour',
                'price' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 5,
                'rental_type' => 'rent by day',
                'price' => '140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 5,
                'rental_type' => 'rent by hour',
                'price' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 6,
                'rental_type' => 'rent by day',
                'price' => '150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 6,
                'rental_type' => 'rent by hour',
                'price' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 7,
                'rental_type' => 'rent by day',
                'price' => '160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 7,
                'rental_type' => 'rent by hour',
                'price' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 8,
                'rental_type' => 'rent by day',
                'price' => '170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 8,
                'rental_type' => 'rent by hour',
                'price' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 9,
                'rental_type' => 'rent by day',
                'price' => '180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 9,
                'rental_type' => 'rent by hour',
                'price' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 10,
                'rental_type' => 'rent by day',
                'price' => '190',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 11,
                'rental_type' => 'rent by hour',
                'price' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 12,
                'rental_type' => 'rent by day',
                'price' => '110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 12,
                'rental_type' => 'rent by hour',
                'price' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 13,
                'rental_type' => 'rent by day',
                'price' => '120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 13,
                'rental_type' => 'rent by hour',
                'price' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 14,
                'rental_type' => 'rent by day',
                'price' => '130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 14,
                'rental_type' => 'rent by hour',
                'price' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 15,
                'rental_type' => 'rent by day',
                'price' => '140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 15,
                'rental_type' => 'rent by hour',
                'price' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 16,
                'rental_type' => 'rent by day',
                'price' => '150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 16,
                'rental_type' => 'rent by hour',
                'price' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 17,
                'rental_type' => 'rent by day',
                'price' => '160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 17,
                'rental_type' => 'rent by hour',
                'price' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 18,
                'rental_type' => 'rent by day',
                'price' => '170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 18,
                'rental_type' => 'rent by hour',
                'price' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 19,
                'rental_type' => 'rent by day',
                'price' => '180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 19,
                'rental_type' => 'rent by hour',
                'price' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 20,
                'rental_type' => 'rent by day',
                'price' => '190',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 20,
                'rental_type' => 'rent by hour',
                'price' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 21,
                'rental_type' => 'rent by day',
                'price' => '100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 21,
                'rental_type' => 'rent by hour',
                'price' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 22,
                'rental_type' => 'rent by day',
                'price' => '110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 22,
                'rental_type' => 'rent by hour',
                'price' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 23,
                'rental_type' => 'rent by day',
                'price' => '120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 23,
                'rental_type' => 'rent by hour',
                'price' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 24,
                'rental_type' => 'rent by day',
                'price' => '130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 24,
                'rental_type' => 'rent by hour',
                'price' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 25,
                'rental_type' => 'rent by day',
                'price' => '140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 25,
                'rental_type' => 'rent by hour',
                'price' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 26,
                'rental_type' => 'rent by day',
                'price' => '150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 26,
                'rental_type' => 'rent by hour',
                'price' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 27,
                'rental_type' => 'rent by day',
                'price' => '160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 27,
                'rental_type' => 'rent by hour',
                'price' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 28,
                'rental_type' => 'rent by day',
                'price' => '170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 28,
                'rental_type' => 'rent by hour',
                'price' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 29,
                'rental_type' => 'rent by day',
                'price' => '180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 29,
                'rental_type' => 'rent by hour',
                'price' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 30,
                'rental_type' => 'rent by day',
                'price' => '190',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 30,
                'rental_type' => 'rent by hour',
                'price' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 31,
                'rental_type' => 'rent by day',
                'price' => '100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'car_id' => 31,
                'rental_type' => 'rent by hour',
                'price' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        //service
        DB::table('service')->insert([
            [
                'title' => 'Trang tri',
                'description' => 'Trang tri cho xe dam cuoi ...',
                'price' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Goi dau',
                'description' => 'Tren xe trang bi san goi dau ...',
                'price' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);


    }
}
